server {
    listen 3000;
    server_name xxxx;

    # H5 静态资源
    root /home/devops;
    index index.html;

    # 前端路由（Vue / React）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API 请求转发到后端
    location /api/ {
        proxy_pass http://127.0.0.1:8000/api/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;   #websocket
        proxy_set_header Upgrade $http_upgrade;   #websocket
        proxy_set_header Connection "upgrade";   #websocket
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 可选：超时（适合日志系统）
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
    }
}